### ISSUE TITLE
Could not resolve "@next-boost/hybrid-disk-cache"

### ISSUE THREAD

**Issue by codejet** [Josh-McFarlin/remix-image#21]
### Describe the bug

I have a site based on https://remix.run/docs/en/v1/tutorials/blog. After installing remix-image and creating a loader, I got this error in the terminal: 

```
 > node_modules/remix-image/build/server.js:1:82: error: Could not resolve "@next-boost/hybrid-disk-cache" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    1 │ ...0});var t=require("@next-boost/hybrid-disk-cache"),e=require("fs")...
      ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Build failed with 1 error:
node_modules/remix-image/build/server.js:1:82: error: Could not resolve "@next-boost/hybrid-disk-cache" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
```

On an earlier version of remix-image I got the error in the browser:

```
Error: Cannot find module 'hybrid-disk-cache'
Require stack:
- /Users/oliver/projects/oliverschmidt-remix/node_modules/remix-image/build/server.js
- /Users/oliver/projects/oliverschmidt-remix/netlify/functions/server/build/index.js
- /Users/oliver/projects/oliverschmidt-remix/netlify/functions/server/index.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/lib/functions/runtimes/js/index.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/lib/functions/runtimes/index.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/lib/functions/registry.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/lib/functions/server.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/commands/dev/dev.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/commands/dev/index.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/commands/main.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/commands/index.js
- /Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/bin/run
  uire stack:
  Users/oliver/projects/oliverschmidt-remix/node_modules/remix-image/build/server.js
  Users/oliver/projects/oliverschmidt-remix/netlify/functions/server/build/index.js
  Users/oliver/projects/oliverschmidt-remix/netlify/functions/server/index.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/lib/functions/runtimes/js/index.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/lib/functions/runtimes/index.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/lib/functions/registry.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/lib/functions/server.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/commands/dev/dev.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/commands/dev/index.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/commands/main.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/src/commands/index.js
  Users/oliver/.nodenv/versions/14.18.1/lib/node_modules/netlify-cli/bin/run
  Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  Function.Module._load (internal/modules/cjs/loader.js:746:27)
  Module.require (internal/modules/cjs/loader.js:974:19)
  require (internal/modules/cjs/helpers.js:93:18)
  Object.<anonymous> (/Users/oliver/projects/oliverschmidt-remix/node_modules/remix-image/build/server.js:1:75)
  Module._compile (internal/modules/cjs/loader.js:1085:14)
  Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  Module.load (internal/modules/cjs/loader.js:950:32)
  Function.Module._load (internal/modules/cjs/loader.js:790:12)
  Module.require (internal/modules/cjs/loader.js:974:19)
```

No idea why this fails on the server as `@next-boost/hybrid-disk-cache` supports CJS afaict. Maybe it is related to the Netlify setup?

### Steps to Reproduce the Bug or Issue

I just followed the steps from your basic tutorial.

### Expected behavior

The image component should work.

### Platform

- OS: macOS
- Browser: Chrome
- Node: v14.18.1

**Comment by Josh-McFarlin** [comment]
Checking before I look into this issue deeper, `@next-boost/hybrid-disk-cache` is a peer dependency and is not included by default. Have you included `@next-boost/hybrid-disk-cache` in your project?

(And to confirm, are you using `diskCache` in your project? Ideally this should only be an error that is thrown when you are using `diskCache` and haven't installed the necessary dependencies.)

**Comment by codejet** [comment]
Hey @Josh-McFarlin, yes, I use `DiskCache` as seen in your example:
```
import { imageLoader, DiskCache } from "remix-image/server";

const config = {
  selfUrl: "http://localhost:3000",
  cache: new DiskCache(),
};

export const loader = ({ request }) => {
  return imageLoader(config, request);
};
```
I wasn't aware I have to install the package. Had just seen that it was listed as a dev dep but missed that it's a peer one, too. So, I thought it could be an SSR issue. But when I install it, that error is gone. I get another one, but it's probably not related to your component.

**Comment by codejet** [comment]
Thanks @Josh-McFarlin 👍

**Comment by andreaspapav** [comment]
Even with the dependency installed I get a similar error.

module.exports.default = isSvg;
                         ^
TypeError: g is not a constructor
    at new DiskCache (/node_modules/is-svg/index.js:41:26)
    at Object.<anonymous> (/app/routes/api/image.tsx:20:10)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)

**Comment by chrisbull** [comment]
getting error with isSvg as well

```
module.exports.default = isSvg;
                         ^
TypeError: g is not a constructor
    at new DiskCache (....../node_modules/is-svg/index.js:41:26)
    at Object.<anonymous> (....../build/index.js:971:10)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Server.<anonymous> (....../build/server.js:44752:3)
    at Object.onceWrapper (node:events:627:28)
ERROR: "dev:server" exited with 1
```

**Comment by Kiyozz** [comment]
> Even with the dependency installed I get a similar error.
> 
> module.exports.default = isSvg; ^ TypeError: g is not a constructor at new DiskCache (/node_modules/is-svg/index.js:41:26) at Object. (/app/routes/api/image.tsx:20:10) at Module._compile (node:internal/modules/cjs/loader:1159:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)



Same here

    @next-boost/hybrid-disk-cache 0.3.0
    remix-image 1.4.0
    remix-image-sharp 0.1.4
    remix ^1.19.3

Using pnpm


```tsx
import { type LoaderArgs } from "@remix-run/node";
import { DiskCache, imageLoader } from "remix-image/server";
import { sharpTransformer } from "remix-image-sharp";

const config = {
  cache: new DiskCache(),
  transformer: sharpTransformer,
};

export async function loader({ request }: LoaderArgs) {
  return imageLoader(
    {
      selfUrl: new URL(request.url).origin,
      ...config,
    },
    request,
  );
}
```

**Comment by niclas-j** [comment]
> > Even with the dependency installed I get a similar error.
> > module.exports.default = isSvg; ^ TypeError: g is not a constructor at new DiskCache (/node_modules/is-svg/index.js:41:26) at Object. (/app/routes/api/image.tsx:20:10) at Module._compile (node:internal/modules/cjs/loader:1159:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
> 
> Same here
> 
> ```
> @next-boost/hybrid-disk-cache 0.3.0
> remix-image 1.4.0
> remix-image-sharp 0.1.4
> remix ^1.19.3
> ```
> 
> Using pnpm
> 
> ```tsx
> import { type LoaderArgs } from "@remix-run/node";
> import { DiskCache, imageLoader } from "remix-image/server";
> import { sharpTransformer } from "remix-image-sharp";
> 
> const config = {
>   cache: new DiskCache(),
>   transformer: sharpTransformer,
> };
> 
> export async function loader({ request }: LoaderArgs) {
>   return imageLoader(
>     {
>       selfUrl: new URL(request.url).origin,
>       ...config,
>     },
>     request,
>   );
> }
> ```

Same issue with pnpm.

**Comment by Loschcode** [comment]
Same here

```
❯ pnpm install @next-boost/hybrid-disk-cache
Already up to date
Progress: resolved 874, reused 818, downloaded 0, added 0, done
Done in 1.8s
❯ npx remix dev

 💿  remix dev

 info  building...
 info  built (1s)

/Users/laurentschaffner/Desktop/work/aquiestoy/applications/website/node_modules/.pnpm/remix-image@1.4.0_@cloudflare+kv-asset-handler@0.2.0_@next-boost+hybrid-disk-cache@0.3.0_reac_dt4jok3sjnhbt66f4gffvwbtsu/node_modules/is-svg/index.js:41
module.exports.default = isSvg;
                         ^
TypeError: g is not a constructor
    at new DiskCache (/Users/laurentschaffner/Desktop/work/aquiestoy/applications/website/node_modules/.pnpm/remix-image@1.4.0_@cloudflare+kv-asset-handler@0.2.0_@next-boost+hybrid-disk-cache@0.3.0_reac_dt4jok3sjnhbt66f4gffvwbtsu/node_modules/is-svg/index.js:41:26)
    at file:///Users/laurentschaffner/Desktop/work/aquiestoy/applications/website/app/routes/api.image.tsx:6:10
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

This problem should be assessed. Also, the documentation is basically deprecated in many ways. Not sure what to do about all this since no one is answering.

**Comment by Kiyozz** [comment]
> Same here
> 
> 
> 
> ```
> 
> ❯ pnpm install @next-boost/hybrid-disk-cache
> 
> Already up to date
> 
> Progress: resolved 874, reused 818, downloaded 0, added 0, done
> 
> Done in 1.8s
> 
> ❯ npx remix dev
> 
> 
> 
>  💿  remix dev
> 
> 
> 
>  info  building...
> 
>  info  built (1s)
> 
> 
> 
> /Users/laurentschaffner/Desktop/work/aquiestoy/applications/website/node_modules/.pnpm/remix-image@1.4.0_@cloudflare+kv-asset-handler@0.2.0_@next-boost+hybrid-disk-cache@0.3.0_reac_dt4jok3sjnhbt66f4gffvwbtsu/node_modules/is-svg/index.js:41
> 
> module.exports.default = isSvg;
> 
>                          ^
> 
> TypeError: g is not a constructor
> 
>     at new DiskCache (/Users/laurentschaffner/Desktop/work/aquiestoy/applications/website/node_modules/.pnpm/remix-image@1.4.0_@cloudflare+kv-asset-handler@0.2.0_@next-boost+hybrid-disk-cache@0.3.0_reac_dt4jok3sjnhbt66f4gffvwbtsu/node_modules/is-svg/index.js:41:26)
> 
>     at file:///Users/laurentschaffner/Desktop/work/aquiestoy/applications/website/app/routes/api.image.tsx:6:10
> 
>     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
> 
> ```
> 
> 
> 
> This problem should be assessed. Also, the documentation is basically deprecated in many ways. Not sure what to do about all this since no one is answering.

A new fork is needed since the latest release was 2 years ago

**Comment by Disorrder** [comment]
+1
