### ISSUE TITLE
MimeType not working!?

### ISSUE THREAD

**Issue by OnlyC** [Josh-McFarlin/remix-image#28]
### Describe the bug

I've tried to display .webp images instead of jpeg to reduce file size but I can't.
Tried 
`defaultOptions`
`set default parameter contentType: outputContentType = MimeType.WEBP in sharpTransformer`
`move .webp() resize to right after image.resize, before .jpeg()`
nothing works. 
`set options={{contentType: MimeType.WEBP}}` does add &contentType=image/webp to the URL

But the responses are all image/jpeg
![image](https://user-images.githubusercontent.com/1250580/164878239-c2b710ea-5fe5-4ec4-903e-28dbdf2b2bd1.png)

### Steps to Reproduce the Bug or Issue

Describe above

### Expected behavior

Response image/webp

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [100.0.4896.127 (Official Build) (64-bit)]

**Comment by Josh-McFarlin** [comment]
Looking into this. When you run this app on localhost, what do the console logs in the server terminal say? It's possible it is falling back to Jpeg for some reason and should hopefully give an explanation why.

**Comment by Josh-McFarlin** [comment]
And to confirm, have you installed the `sharp` package? If not, the `sharpTransformer` will throw an error and fall back to the default pure js transformer.

**Comment by OnlyC** [comment]
Yes, `sharp` installed.
Console logs (cache: null): 
![image](https://user-images.githubusercontent.com/1250580/164932833-be2ec86e-f75b-4080-8e1e-afcb6e2347a4.png)

**Comment by Josh-McFarlin** [comment]
Yep, looks like Sharp is working as intended. So definitely something wrong with the inputs being provided to Sharp. Those server logs suggest the image request is not asking for WebP however, it should say something at the end along the lines of `&width=640&contentType=image%2Fwebp` like in your first photo. Could you send some console output when a WebP request is made? 

(If you are making a WebP request, and the browser devtools shows WebP is being sent in the params, this likely means something is going wrong with the URL parsing)

**Comment by OnlyC** [comment]
![image](https://user-images.githubusercontent.com/1250580/164934716-8fce18db-37de-4681-945e-bdbabcda2fdc.png)

The only way to add &contentType=image/webp to request is to add options:
![image](https://user-images.githubusercontent.com/1250580/164934917-bdd486f9-1ff6-4321-b09c-e460c11a3301.png)

Response header still image/jpeg.

**Comment by Josh-McFarlin** [comment]
Found the issue, one moment!

**Comment by Josh-McFarlin** [comment]
@OnlyC, please try updating to the newest version `0.3.18`

**Comment by OnlyC** [comment]
Thank you! Working as expected!

**Comment by tomekrozalski** [comment]
@Josh-McFarlin I cannot reopen that

**Comment by Josh-McFarlin** [comment]
@tomekrozalski I'm assuming in this case you are only trying to convert the image to WebP, and not make it responsive at all?

When I originally wrote this library, I only had resizing in mind, so the library would never make any requests if the `responsive` property is empty. However, I'm definitely open to changing this!

**Comment by tomekrozalski** [comment]
@Josh-McFarlin Yes, this is a case when I do not want to resize, but only to change file format. I agree, we should use it with resizing though - that is why I believe the `responsive` should never be empty. It should not have `?` here:

https://github.com/Josh-McFarlin/remix-image/blob/master/src/components/Image/Image.tsx#L9

Moreover we could type it as follows:

```
responsive: [ResponsiveSize, ...ResponsiveSize[]]
```

to make sure at least one `responsive` object was set. I am not sure, that is just quick thought 🤔
