### ISSUE TITLE
Responsive sizes handling `min-width`

### ISSUE THREAD

**Issue by kwiat1990** [Josh-McFarlin/remix-image#31]
### Describe the bug

Hi, I would like to load a bigger image on mobile and smaller on desktop. Normally I would define on `img` HTML tag a `min-width` or if needed both min and max like so: 
```
sizes="
  ((min-width: 50em) and (max-width: 60em)) 50em,
  ((min-width: 30em) and (max-width: 50em)) 30em,
  (max-width: 30em) 20em"
 ``` 

But the component accepts only `max-width` and it won't work in my case, where the bigger images should be loaded on smaller screen. Currently my code looks following (smaller images are loaded on both mobile and desktop):

```tsx
responsive={[
  {
    size: {
       width: Math.round(cover.width / 2),
       height: Math.round(cover.height / 2),
     },
     maxWidth: 768,
  },
  {
     size: {
      width: Math.round(cover.width / 4),
      height: Math.round(cover.height / 4),
    },
    maxWidth: 1200
  },
]}
```

Am I missing something or it can work as I expect it with the current implementation of `Remix-Image`? 

### Steps to Reproduce the Bug or Issue

Define in `responsive` prop two image sizes: for mobile bigger images should be displayed and for desktop smaller ones.

### Expected behavior

I would like to defined also a min-width to display images.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tomekrozalski** [comment]
@kwiat1990 That is how the library works, we can use `maxWidth` only. In your scenario:

```
sizes="
  ((min-width: 50em) and (max-width: 60em)) 50em,
  ((min-width: 30em) and (max-width: 50em)) 30em,
  (max-width: 30em) 20em"
```

You need to reverse the order:

```
sizes="
  (max-width: 30em) 20em,
  (max-width: 50em) 30em,
  50em,
  "
```

A browser will pick first image which meets the conditions. I believe it is quite readable.

**Comment by kwiat1990** [comment]
The above example comes from MDN page for `sizes` docs. 

I have played with `sizes` and `maxWidth` (I have also tried to omit) but I can't really achieve what I want: load smaller images on desktop and bigger on mobile. Instead, smaller images are loaded on both.

The real code I use is following:
```tsx
responsive={[
  {
    size: {
       width: Math.round(cover.width / 2),
       height: Math.round(cover.height / 2),
     },
     maxWidth: 768,
  },
  {
     size: {
      width: Math.round(cover.width / 4),
      height: Math.round(cover.height / 4),
    },
  },
]}
```

**Comment by tomekrozalski** [comment]
@kwiat1990 I see it now. You are right, something is wrong here, the order of `sizes="400px, (max-width: 769px) 800px"` is wrong, it should not be sorted.

**Comment by kwiat1990** [comment]
I think that too. If the original order would be kept, then it should work as I wanted.

**Comment by Josh-McFarlin** [comment]
I found sorting helped resolve a bug that occurred when the screen was larger than any of the `sizes`, but we can definitely remove sorting.

**Comment by tomekrozalski** [comment]
Maybe we need to sort by `maxWidth` instead? From the smallest to largest and values without `maxWidth` at the end?
I created pull request: https://github.com/Josh-McFarlin/remix-image/pull/34/files

**Comment by Josh-McFarlin** [comment]
@tomekrozalski Thanks for the PR! Currently relocating for work, so I'll review it later today and hopefully push out a new release.
