### ISSUE TITLE
Loader option `fit` does not work

### ISSUE THREAD

**Issue by tomekrozalski** [Josh-McFarlin/remix-image#32]
### Describe the bug

When I try to load an image which is rectangular and crop it to square:

```
<Image
  alt=""
  options={{
    fit: ImageFit.COVER,
  }}
  responsive={[
    {
      maxWidth: 800,
      size: {
        height: 800,
        width: 800,
      },
    },
  ]}
  src="https://images.unsplash.com/photo-1655241459367-c95abd34d0bc"
/>
```

It does not work, the image is distorted, it is not cropped. This part in url `&width=800&height=800&fit=cover` does not give me anything. On the other hand it works on unsplash (`&fit=crop&w=500&h=500&q=80`): https://images.unsplash.com/photo-1655241459367-c95abd34d0bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&h=500&q=80

What I do wrong? :)

### Steps to Reproduce the Bug or Issue

Try to create `<Image />` with option `fit: ImageFit.COVER`. Inspect the image. It is not cropped.

### Expected behavior

When we use `fit: ImageFit.COVER` and provided size of an image is different from its own ratio - it should be cropped.

### Screenshots or Videos

![Screenshot 2022-06-15 at 12 34 00](https://user-images.githubusercontent.com/11705681/173807276-a017c51d-9fa6-4483-a630-318b6e63b217.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tomekrozalski** [comment]
It works fine when I use `sharp` transformer from documentation (remember to remove `.tmp/` folder after changing transformer). So maybe in this case that is the solution.

**Comment by Josh-McFarlin** [comment]
Unfortunately that's a limitation of the `pureTransformer` (that has been extracted to the package [js-image-lib](https://www.npmjs.com/package/js-image-lib))

I originally wrote this library using Sharp by default, but I realized a pure js default would be better in order to support Cloudflare. 

js-image-lib does not currently support this operation, but it's on the timeline. If you are interested in contributing, feel free to work on this issue! Otherwise, this is the reason why the documentation highly recommends using Sharp without using it by default.

**Comment by Josh-McFarlin** [comment]
Great! In the meantime, if your use case will always require square images, you can crop the image first: https://remix-image.mcfarl.in/docs/component#transformoptions

**Comment by Josh-McFarlin** [comment]
```
export interface CropOptions {
  /** The x position of the upper left pixel. */
  x: number;
  /** The y position of the upper left pixel. */
  y: number;
  /** The number of pixels wide to crop the image. */
  width: number;
  /** The number of pixels high to crop the image. */
  height: number;
}
```

**Comment by Josh-McFarlin** [comment]
@tomekrozalski Just wanted to mention that I incorporated changes into the latest releases of js-image-lib and Remix-Image to support `fit` and `position` in pureTransformer, so they can be used on all environments, not just those that support using Sharp
