### ISSUE TITLE
WEBP - Transformers Error

### ISSUE THREAD

**Issue by derhoerit** [Josh-McFarlin/remix-image#44]
### Describe the bug

I try to run vercel examples when i change src to .webp format the image is corrupt 

### Steps to Reproduce the Bug or Issue

1. Clone Vercel Examples
2. Run Remix
3. Try change src from camera.png to camera.webp
4. The images is crash

### Expected behavior

Image is resized

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [13]

**Comment by Josh-McFarlin** [comment]
Looking into this. To clone the Vercel example, did you clone the entire Remix-Image repo and are trying to run it from inside there? Or did you copy just the Vercel example directory? Moving this repo to a monorepo has caused some problems with the examples setup that I haven't entirely fixed yet.

**Comment by Josh-McFarlin** [comment]
Hey @derhoerit,

After looking into it, I found out that ensuring the image had an alpha channel was clearing all the image data for WebP images only. After changing this, it appears to be working correctly. Please update to the latest `remix-image-sharp` and let me know if the problem still occurs.

Thanks!
